#!/bin/sh

cd /Users/louissaint-raymond2/Documents/Louis/Robotique/Raspberry/Python/images/

scp -r pi@raspberrypi.local:Desktop/Robotique/images/test/ .

#scp  pi@raspberrypi.local:Desktop/Robotique/COMwithArduino.py .